### ISSUE TITLE
Extending an array config only overrides specific elements of the array

### ISSUE THREAD

**Issue by danepowell** [consolidation/config#31]
I'm opening this in reference to a downstream issue with BLT (which uses consolidation/config): https://github.com/acquia/blt/issues/3697

BLT works by providing a default set of configuration, and then calling ConfigProcessor::extend() to override any values with user-provided variants (via blt.yml and other sources).

As you can see from that issue, the problem this user is facing is that when they want to override an array, they have to override every element of that array individually. I think it would make more sense that if you override any part of an array, it resets the entire array.

For instance, if the array is this:

```yaml
sync:
  commands:
    - op1
    - op2
```

We extend it as:

```yaml
sync:
  commands:
    - opfoo
```

We expect the final overridden config to be:

```yaml
sync:
  commands:
    - opfoo
```

But we actually get:

 ```yaml
sync:
  commands:
    - opfoo
    - op2
```

Is this expected behavior? Is there some other workaround that I'm missing?
